### ISSUE TITLE
Some tensors are in CUDA other in CPU

### ISSUE THREAD

**Issue by yquemener** [schen149/sub-sentence-encoder#1]
At step #3 I was met with the following errors:

`
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
`

I could solve it by writing the following function:

```
def to_cuda(i):
    i.all_prop_mask = i.all_prop_mask.cuda()
    i.num_prop_per_sentence=i.num_prop_per_sentence.cuda()
    for k,v in i.encoder_inputs.data.items():
        i.encoder_inputs.data[k]=v.cuda()
    return i
```

Then passing the inputs through it:

```
to_cuda(sent1_inputs)
to_cuda(sent2_inputs)
```

then step #3 executed without problem

**Comment by schen149** [comment]
We actually have an implementation of this in `PropPairModelInput` --  https://github.com/schen149/sub-sentence-encoder/blob/490d3d0a7b625e392dcf031d428267a3a7ca5539/utils/data_utils.py#L54-L61

So you can simply do --
```
sent1_inputs.to("cuda")
sent2_inputs.to("cuda")
```

Thanks for bringing it up though! We've added this bit to our instructions.
